name: Publish Build

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  preparerelease:
    runs-on: ubuntu-latest
    env:
      NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Parse version
        run: echo "version=$(echo ${{ inputs.branch }} | rev | cut -d '/' -f 1 | rev)" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          ref: release/${{ env.version }}

      - run: sed -i "s/.*<Version>\(.*\)<\/Version>/    <Version>$version<\/Version>/" Server/*.csproj

      - run: git status
      - run: git config user.email "action@github.com"
      - run: git config user.name "Github Action"
      - run: git diff --quiet HEAD || (git commit -a -m "Version set" && git tag ${{ env.version }})

      - if: ${{ !contains(env.version, '-') }}
        run: sed -i "s/.*<Version>[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)\([0-9A-Za-z-]*\)<\/Version>/    <Version>\1.$(($(echo $version | cut -d '.' -f 2) + 1)).\3\$(VersionSuffix)<\/Version>/" Server/*.csproj && git commit -a -m "Next version set"

      - run: git push && git push --tags
